name: ml
channels:
  - conda-forge
  - huggingface
  - pytorch
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - absl-py=2.1.0=py312hecd8cb5_0
  - aiohappyeyeballs=2.4.0=py312hecd8cb5_0
  - aiohttp=3.10.5=py312h46256e1_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alembic=1.8.1=py312hecd8cb5_0
  - altair=5.0.1=py312hecd8cb5_0
  - anchor-exp=0.0.2.0=pyhd8ed1ab_0
  - aniso8601=9.0.1=pyhd3eb1b0_0
  - annotated-types=0.6.0=py312hecd8cb5_0
  - anyio=4.2.0=py312hecd8cb5_0
  - aom=3.9.1=hf036a51_0
  - appnope=0.1.3=py312hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h6c40b1e_0
  - arrow-cpp=13.0.0=h694c41f_49_cpu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-lru=2.0.4=py312hecd8cb5_0
  - atk-1.0=2.36.0=hb642b71_0
  - attrs=23.1.0=py312hecd8cb5_0
  - autoviz=0.1.720=pyhd8ed1ab_0
  - aws-c-auth=0.7.22=hb04b931_10
  - aws-c-cal=0.7.1=hd73d8db_1
  - aws-c-common=0.9.23=hfdf4475_0
  - aws-c-compression=0.2.18=hd73d8db_7
  - aws-c-event-stream=0.4.2=h2713d70_15
  - aws-c-http=0.8.2=he29c2fd_6
  - aws-c-io=0.14.10=h4406d91_1
  - aws-c-mqtt=0.10.4=hf6997d9_8
  - aws-c-s3=0.6.0=h13137a3_2
  - aws-c-sdkutils=0.1.16=hd73d8db_3
  - aws-checksums=0.1.18=hd73d8db_7
  - aws-crt-cpp=0.27.3=h0a15bd7_2
  - aws-sdk-cpp=1.11.329=h554caeb_9
  - awswrangler=3.9.1=pyhd8ed1ab_0
  - babel=2.11.0=py312hecd8cb5_0
  - bcrypt=3.2.0=py312h6c40b1e_1
  - beautifulsoup4=4.12.3=py312hecd8cb5_0
  - black=24.8.0=py312hecd8cb5_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py312hecd8cb5_0
  - blosc=1.21.6=h7d75f6d_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boto3=1.34.154=py312hecd8cb5_0
  - botocore=1.34.154=py312hecd8cb5_0
  - bottleneck=1.3.7=py312h32608ca_0
  - brotli=1.0.9=hb1e8313_2
  - brotli-bin=1.1.0=h00291cd_2
  - brotli-python=1.0.9=py312hcec6c5f_8
  - brunsli=0.1=h23ab428_0
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.33.1=h44e7173_0
  - c-blosc2=2.14.4=h0ae8482_1
  - ca-certificates=2024.8.30=h8857fd0_0
  - cached-property=1.5.2=py_0
  - cairo=1.18.0=h9f650ed_2
  - catalogue=2.0.10=py312hecd8cb5_0
  - catboost=1.2.3=py312hecd8cb5_0
  - category_encoders=2.6.3=py312hecd8cb5_0
  - cctools_osx-64=949.0.1=hc7db93f_25
  - certifi=2024.8.30=py312hecd8cb5_0
  - cffi=1.16.0=py312h6c40b1e_1
  - charls=2.4.2=he965462_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - clang=14.0.6=hecd8cb5_1
  - clang-14=14.0.6=default_hd95374b_1
  - clang_osx-64=14.0.6=hb1e4b1b_0
  - clangxx=14.0.6=default_hd95374b_1
  - clangxx_osx-64=14.0.6=hd8b9576_0
  - click=8.1.7=py312hecd8cb5_0
  - cloudpathlib=0.16.0=py312hecd8cb5_1
  - cloudpickle=3.0.0=py312hecd8cb5_0
  - cmdstan=2.33.1=h33b0451_0
  - cmdstanpy=1.1.0=py312hecd8cb5_0
  - colorama=0.4.6=py312hecd8cb5_0
  - colorcet=3.1.0=py312hecd8cb5_0
  - colorlog=5.0.1=py312hecd8cb5_1
  - comm=0.2.1=py312hecd8cb5_0
  - compiler-rt=14.0.6=hda8b6b8_0
  - compiler-rt_osx-64=14.0.6=h8d5cb93_0
  - confection=0.1.4=py312h8e4b320_0
  - contourpy=1.2.0=py312ha357a0b_0
  - cryptography=43.0.0=py312h30e54ef_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.6=py312hcec6c5f_0
  - cyrus-sasl=2.1.27=hf9bab2b_7
  - cython-blis=0.7.11=py312h32608ca_0
  - cytoolz=0.12.2=py312h6c40b1e_0
  - dacite=1.8.1=py312hecd8cb5_0
  - dask=2024.8.2=pyhd8ed1ab_0
  - dask-core=2024.8.2=py312hecd8cb5_0
  - dask-expr=1.1.13=pyhd8ed1ab_0
  - dask-glm=0.2.0=pyhd3eb1b0_0
  - dask-ml=2024.4.4=py312hecd8cb5_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datasets=3.0.0=py_0
  - dav1d=1.2.1=h6c40b1e_0
  - debugpy=1.6.7=py312hcec6c5f_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diffusers=0.18.2=py312h8e4b320_0
  - diffusers-base=0.18.2=py312h8e4b320_0
  - diffusers-torch=0.18.2=py312h8e4b320_0
  - dill=0.3.8=py312hecd8cb5_0
  - distributed=2024.8.2=py312hecd8cb5_0
  - dm-tree=0.1.7=py312hcec6c5f_1
  - docker-py=7.0.0=py312hecd8cb5_0
  - dowhy=0.8=pyhd8ed1ab_0
  - emoji=2.12.1=pyhd8ed1ab_0
  - entrypoints=0.4=py312hecd8cb5_0
  - etils=1.9.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6d0c2b6_0
  - filelock=3.13.1=py312hecd8cb5_0
  - flake8=7.1.1=py312hecd8cb5_0
  - flask=3.0.3=py312hecd8cb5_0
  - flatbuffers=24.3.25=h6d0c2b6_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py312h6c40b1e_0
  - freetype=2.12.1=h60636b9_2
  - fribidi=1.0.10=haf1e3a3_0
  - frozenlist=1.4.0=py312h6c40b1e_0
  - fsspec=2024.6.1=py312hecd8cb5_0
  - gast=0.5.3=pyhd3eb1b0_0
  - gdk-pixbuf=2.42.12=ha587570_0
  - gensim=4.3.3=py312h77d3abe_0
  - gettext=0.21.1=h8a4c099_0
  - gflags=2.2.2=hcec6c5f_1
  - giflib=5.2.2=h10d778d_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py312hecd8cb5_0
  - glib=2.80.3=h736d271_2
  - glib-tools=2.80.3=h959cb30_2
  - glog=0.7.1=h2790a97_0
  - gobject-introspection=1.78.1=py312hf6ed2c1_1
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - googleapis-common-protos=1.63.2=py312hecd8cb5_0
  - graphene=3.3=py312hecd8cb5_0
  - graphite2=1.3.14=he9d5cce_1
  - graphql-core=3.2.3=py312hecd8cb5_1
  - graphql-relay=3.2.0=py312hecd8cb5_0
  - graphviz=9.0.0=hee74176_1
  - greenlet=3.0.1=py312hcec6c5f_0
  - grpcio=1.62.2=py312hbbbd34f_0
  - gst-plugins-base=1.24.7=h0ee1d58_0
  - gstreamer=1.24.7=h3271b85_0
  - gtk2=2.24.33=h4d89f74_2
  - gts=0.7.6=h6759243_3
  - gunicorn=22.0.0=py312hecd8cb5_0
  - h11=0.14.0=py312hecd8cb5_0
  - h5py=3.11.0=nompi_py312hfc94b03_102
  - harfbuzz=9.0.0=h053f038_0
  - hdf5=1.14.3=nompi_h687a608_105
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holidays=0.48=py312hecd8cb5_0
  - holoviews=1.14.8=pyhd3eb1b0_0
  - htmlmin=0.1.12=pyhd3eb1b0_1
  - httpcore=1.0.2=py312hecd8cb5_0
  - httpx=0.27.0=py312hecd8cb5_0
  - huggingface_accelerate=0.33.0=py312hecd8cb5_0
  - huggingface_hub=0.24.7=pyhd8ed1ab_0
  - hvplot=0.7.3=pyhd3eb1b0_1
  - icu=73.2=hf5e326d_0
  - idna=3.7=py312hecd8cb5_0
  - imagecodecs=2024.1.1=py312hb18e1f5_6
  - imagehash=4.3.1=py312hecd8cb5_0
  - imageio=2.33.1=py312hecd8cb5_0
  - imbalanced-learn=0.12.3=py312hecd8cb5_1
  - importlib-metadata=7.0.1=py312hecd8cb5_0
  - importlib-resources=6.4.0=pyhd3eb1b0_0
  - importlib_resources=6.4.0=py312hecd8cb5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2022.1.0=haf03e11_3719
  - ipykernel=6.28.0=py312hecd8cb5_0
  - ipython=8.25.0=py312hecd8cb5_0
  - ipywidgets=8.1.2=py312hecd8cb5_0
  - iso3166=2.1.1=pyhd8ed1ab_0
  - isort=5.13.2=py312hecd8cb5_0
  - itsdangerous=2.2.0=py312hecd8cb5_0
  - jedi=0.19.1=py312hecd8cb5_0
  - jinja2=3.1.4=py312hecd8cb5_0
  - jmespath=1.0.1=py312hecd8cb5_0
  - joblib=1.4.2=py312hecd8cb5_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312hecd8cb5_0
  - jsonschema-specifications=2023.7.1=py312hecd8cb5_0
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=py312hecd8cb5_0
  - jupyter_client=8.6.0=py312hecd8cb5_0
  - jupyter_console=6.6.3=py312hecd8cb5_1
  - jupyter_core=5.7.2=py312hecd8cb5_0
  - jupyter_events=0.10.0=py312hecd8cb5_0
  - jupyter_server=2.14.1=py312hecd8cb5_0
  - jupyter_server_terminals=0.4.4=py312hecd8cb5_1
  - jupyterlab=4.2.5=py312hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312hecd8cb5_0
  - jupyterlab_widgets=3.0.10=py312hecd8cb5_0
  - jxrlib=1.1=haf1e3a3_2
  - keras=3.0.5=py312hecd8cb5_0
  - keras-core=0.1.7=pyhd8ed1ab_0
  - keras-tuner=1.4.7=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py312hcec6c5f_0
  - krb5=1.21.3=h37d8d59_0
  - kt-legacy=1.0.5=pyhd8ed1ab_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lazy_loader=0.4=py312hecd8cb5_0
  - lcms2=2.16=ha2f27b4_0
  - ld64_osx-64=530=h70f3046_25
  - ldid=2.1.5=hc58f1be_3
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20240116.2=cxx17_h548131f_0
  - libaec=1.1.3=h73e2aa4_0
  - libarrow=13.0.0=h6d820dd_49_cpu
  - libavif16=1.1.1=ha49a9e2_1
  - libbrotlicommon=1.1.0=h00291cd_2
  - libbrotlidec=1.1.0=h00291cd_2
  - libbrotlienc=1.1.0=h00291cd_2
  - libclang=14.0.6=default_hd95374b_1
  - libclang-cpp14=14.0.6=default_hd95374b_1
  - libclang13=14.0.6=default_habbcc1a_1
  - libcrc32c=1.1.2=he9d5cce_0
  - libcurl=8.10.0=h58e7537_0
  - libcxx=18.1.8=hd876a4e_7
  - libdeflate=1.20=h49d49c5_0
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h04015c4_1
  - libexpat=2.6.3=hac325c4_0
  - libffi=3.4.2=h0d85af4_5
  - libgd=2.3.3=h0dceb68_9
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libglib=2.80.3=h736d271_2
  - libgoogle-cloud=2.26.0=h721cda5_0
  - libgoogle-cloud-storage=2.26.0=h9e84e37_0
  - libgrpc=1.62.2=h384b2fc_0
  - libhwy=1.1.0=h7728843_0
  - libiconv=1.17=hd75f5a5_2
  - libintl=0.22.5=hdfe23c8_3
  - libintl-devel=0.22.5=hdfe23c8_3
  - libjpeg-turbo=3.0.3=h46256e1_0
  - libjxl=0.10.3=hfb90b89_0
  - libllvm14=14.0.6=hc8e404f_4
  - libnghttp2=1.58.0=h64cf6d3_1
  - libntlm=1.6=h9ed2024_0
  - libogg=1.3.5=hca72f7f_1
  - libopenblas=0.3.21=h54e7dc3_0
  - libopus=1.3.1=h1de35cc_0
  - libpng=1.6.43=h92b6c6a_0
  - libpq=16.4=h75a757a_1
  - libprotobuf=4.25.3=h4e4d658_0
  - libre2-11=2023.09.01=h81f5012_2
  - librsvg=2.58.4=h2682814_0
  - libsodium=1.0.18=h1de35cc_0
  - libsqlite=3.46.0=h1b8f9f3_0
  - libssh2=1.11.0=hd019ec5_0
  - libthrift=0.19.0=h064b379_1
  - libtiff=4.6.0=h129831d_3
  - libutf8proc=2.8.0=hb7f2c08_0
  - libvorbis=1.3.7=haf1e3a3_0
  - libwebp=1.3.2=h44782d1_1
  - libwebp-base=1.3.2=h6c40b1e_0
  - libxcb=1.15=hb7f2c08_0
  - libxgboost=2.1.1=hab2016f_0
  - libxml2=2.12.7=hc603aa4_3
  - libzlib=1.3.1=h87427d6_1
  - libzopfli=1.0.3=hb1e8313_0
  - lime=0.2.0.1=py312hecd8cb5_0
  - llvm-openmp=18.1.8=h15ab845_1
  - llvm-tools=14.0.6=hc8e404f_4
  - llvmlite=0.43.0=py312h6d0c2b6_0
  - locket=1.0.0=py312hecd8cb5_0
  - lux=0.5.1=pyhd8ed1ab_0
  - lux-api=0.3.1=pyhd8ed1ab_0
  - lux-widget=0.1.11=pyhd8ed1ab_0
  - lz4=4.3.2=py312h6c40b1e_0
  - lz4-c=1.9.4=hcec6c5f_1
  - macports-legacy-support=1.3.0=hfdf4475_0
  - make=4.2.1=h3efe00b_1
  - mako=1.2.3=py312hecd8cb5_0
  - markdown=3.4.1=py312hecd8cb5_0
  - markdown-it-py=2.2.0=py312hecd8cb5_1
  - markupsafe=2.1.3=py312h6c40b1e_0
  - matplotlib=3.8.4=py312hecd8cb5_0
  - matplotlib-base=3.8.4=py312h7f12edd_0
  - matplotlib-inline=0.1.6=py312hecd8cb5_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py312hecd8cb5_0
  - mistune=2.0.4=py312hecd8cb5_0
  - mkl=2023.2.0=h54c2260_50500
  - mkl-service=2.4.0=py312h6c40b1e_1
  - mkl_fft=1.3.8=py312h6c40b1e_0
  - mkl_random=1.2.4=py312ha357a0b_0
  - ml_dtypes=0.3.1=py312he282a81_0
  - mlflow=2.12.2=py312h70df568_0
  - mpmath=1.3.0=py312hecd8cb5_0
  - msgpack-python=1.0.3=py312ha357a0b_0
  - multidict=6.0.4=py312h6c40b1e_0
  - multimethod=1.9.1=py312hecd8cb5_0
  - multipledispatch=0.6.0=py312hecd8cb5_0
  - multiprocess=0.70.15=py312hecd8cb5_0
  - murmurhash=1.0.7=py312hcec6c5f_0
  - mypy_extensions=1.0.0=py312hecd8cb5_0
  - mysql=8.3.0=h88f4db0_4
  - mysql-client=8.3.0=hbece87f_4
  - mysql-common=8.3.0=hfd7a639_4
  - mysql-devel=8.3.0=hfd7a639_4
  - mysql-libs=8.3.0=ha9146f8_4
  - mysql-server=8.3.0=hf319a18_4
  - namex=0.0.7=py312hecd8cb5_0
  - nbclient=0.8.0=py312hecd8cb5_0
  - nbconvert=7.10.0=py312hecd8cb5_0
  - nbconvert-core=7.10.0=pyhd8ed1ab_0
  - nbformat=5.9.2=py312hecd8cb5_0
  - ncurses=6.5=hf036a51_1
  - nest-asyncio=1.6.0=py312hecd8cb5_0
  - networkx=3.3=py312hecd8cb5_0
  - ninja=1.10.2=hecd8cb5_5
  - ninja-base=1.10.2=haf03e11_5
  - nltk=3.9.1=py312hecd8cb5_0
  - notebook=7.2.2=py312hecd8cb5_0
  - notebook-shim=0.2.3=py312hecd8cb5_0
  - numba=0.60.0=py312h77d3abe_0
  - numexpr=2.8.7=py312hac873b0_0
  - numpy=1.26.4=py312hac873b0_0
  - numpy-base=1.26.4=py312h6f81483_0
  - openjpeg=2.5.2=hbf2204d_0
  - openssl=3.3.2=hd23fc13_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optuna=4.0.0=pyhd8ed1ab_0
  - orc=2.0.1=hf43e91b_1
  - overrides=7.4.0=py312hecd8cb5_0
  - packaging=23.2=py312hecd8cb5_0
  - pandas=2.2.2=py312h77d3abe_0
  - pandas-dq=1.28=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.12.6=pyhd3eb1b0_0
  - pango=1.54.0=h115fe74_2
  - param=1.13.0=py312hecd8cb5_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py312hecd8cb5_0
  - pathos=0.3.0=py312hecd8cb5_0
  - pathspec=0.10.3=py312hecd8cb5_0
  - patsy=0.5.6=py312hecd8cb5_0
  - pcre2=10.44=h7634a1b_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - phik=0.12.3=py312ha357a0b_0
  - pillow=10.3.0=py312h0c923fa_0
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.4=h73e2aa4_0
  - platformdirs=3.10.0=py312hecd8cb5_0
  - plotly=5.22.0=py312h8e4b320_0
  - pluggy=1.0.0=py312hecd8cb5_1
  - ply=3.11=py312hecd8cb5_1
  - polars=1.6.0=py312h3598bc1_0
  - pox=0.3.3=py312hecd8cb5_0
  - ppft=1.7.6.7=py312hecd8cb5_0
  - preshed=3.0.6=py312hcec6c5f_0
  - prometheus_client=0.14.1=py312hecd8cb5_0
  - promise=2.3=py312hecd8cb5_0
  - prompt-toolkit=3.0.43=py312hecd8cb5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - prophet=1.1.5=py312h1962661_0
  - protobuf=4.25.3=py312h43dadc6_0
  - protobuf3-to-dict=0.1.5=py312hb401068_9
  - psutil=5.9.0=py312h6c40b1e_0
  - pthread-stubs=0.3=hdd91f34_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.1.1=cpu_pyhb442362_0
  - py4j=0.10.9.7=py312hecd8cb5_0
  - pyamg=4.2.3=py312h44cbcf4_0
  - pyarrow=13.0.0=py312h2822cde_49_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycodestyle=2.12.1=py312hecd8cb5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py312hecd8cb5_0
  - pydantic=2.8.2=py312hecd8cb5_0
  - pydantic-core=2.20.1=py312hcc58cb1_0
  - pydot=3.0.1=py312hb401068_0
  - pyflakes=3.2.0=py312hecd8cb5_0
  - pygments=2.15.1=py312hecd8cb5_1
  - pynacl=1.5.0=py312h6c40b1e_0
  - pyparsing=3.0.9=py312hecd8cb5_0
  - pyqt5-sip=12.13.0=py312h6c40b1e_0
  - pysocks=1.7.1=py312hecd8cb5_0
  - pyspark=3.4.1=py312hecd8cb5_0
  - pytest=7.4.4=py312hecd8cb5_0
  - python=3.12.3=h1411813_0_cpython
  - python-dateutil=2.9.0post0=py312hecd8cb5_2
  - python-fastjsonschema=2.16.2=py312hecd8cb5_0
  - python-flatbuffers=24.3.25=py312hecd8cb5_0
  - python-json-logger=2.0.7=py312hecd8cb5_0
  - python-lmdb=1.4.1=py312hcec6c5f_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py312h6c40b1e_1
  - python_abi=3.12=5_cp312
  - pytorch=2.2.2=py3.12_0
  - pytz=2024.1=py312hecd8cb5_0
  - pyviz_comms=3.0.2=py312hecd8cb5_0
  - pywavelets=1.7.0=py312h46256e1_0
  - pyyaml=6.0.1=py312h6c40b1e_0
  - pyzmq=25.1.2=py312hcec6c5f_0
  - qtpy=2.4.1=py312hecd8cb5_0
  - querystring_parser=1.2.4=py312hecd8cb5_0
  - rav1e=0.6.6=h7205ca4_2
  - re2=2023.09.01=hb168e87_2
  - readline=8.2=h9e318b2_1
  - referencing=0.30.2=py312hecd8cb5_0
  - regex=2024.7.24=py312h46256e1_0
  - requests=2.32.3=py312hecd8cb5_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rfc3339-validator=0.1.4=py312hecd8cb5_0
  - rfc3986-validator=0.1.1=py312hecd8cb5_0
  - rich=13.7.1=py312hecd8cb5_0
  - rpds-py=0.10.6=py312hf2ad997_0
  - s3transfer=0.10.1=py312hecd8cb5_0
  - safetensors=0.4.4=py312hbc49121_0
  - sagemaker=2.75.1=pyhd8ed1ab_0
  - scikit-image=0.23.2=py312h77d3abe_0
  - scikit-learn=1.5.2=py312h9d777eb_1
  - scipy=1.13.0=py312h81688c2_0
  - seaborn=0.13.2=py312hecd8cb5_0
  - send2trash=1.8.2=py312hecd8cb5_0
  - setuptools=73.0.1=pyhd8ed1ab_0
  - shap=0.42.1=py312he282a81_0
  - shellingham=1.5.0=py312hecd8cb5_0
  - sip=6.7.12=py312hcec6c5f_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.7=pyhd3eb1b0_0
  - smart_open=5.2.1=py312hecd8cb5_0
  - smdebug-rulesconfig=1.0.1=pyhd3deb0d_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h6d0c2b6_0
  - sniffio=1.3.0=py312hecd8cb5_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py312hecd8cb5_0
  - spacy=3.7.2=py312h44cbcf4_0
  - spacy-legacy=3.0.12=py312hecd8cb5_0
  - spacy-loggers=1.0.4=py312hecd8cb5_0
  - sqlalchemy=2.0.34=py312hd53568b_0
  - sqlite=3.22.0=h3efe00b_0
  - sqlparse=0.4.4=py312hecd8cb5_0
  - srsly=2.4.8=py312hcec6c5f_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.2=py312ha2b695f_0
  - svt-av1=2.2.1=hac325c4_0
  - sweetviz=2.3.1=pyhd8ed1ab_0
  - sympy=1.13.2=py312hecd8cb5_0
  - tapi=1000.10.8=ha1b3eb9_0
  - tbb=2021.8.0=ha357a0b_0
  - tbb-devel=2021.8.0=ha357a0b_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.2.3=py312hecd8cb5_0
  - tensorboard=2.16.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py312hf1618be_1
  - tensorflow=2.16.1=cpu_py312hfc37b44_0
  - tensorflow-base=2.16.1=cpu_py312h2571b1d_0
  - tensorflow-datasets=4.8.3=pyhd8ed1ab_0
  - tensorflow-estimator=2.16.1=cpu_py312ha140142_0
  - tensorflow-metadata=1.15.0=pyhd8ed1ab_0
  - termcolor=2.1.0=py312hecd8cb5_0
  - terminado=0.17.1=py312hecd8cb5_0
  - textblob=0.18.0.post0=py312h8e4b320_0
  - thinc=8.2.2=py312h44cbcf4_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2023.4.12=py312hecd8cb5_0
  - tinycss2=1.2.1=py312hecd8cb5_0
  - tk=8.6.13=h1abcd95_1
  - tokenizers=0.19.1=py312hfa73619_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py312hecd8cb5_0
  - torchaudio=2.2.2=py312_cpu
  - torchvision=0.17.2=py312_cpu
  - tornado=6.4.1=py312h46256e1_0
  - tqdm=4.66.5=py312h8e4b320_0
  - traitlets=5.14.3=py312hecd8cb5_0
  - transformers=4.41.2=py312hecd8cb5_0
  - typeguard=4.2.1=py312hecd8cb5_0
  - typer=0.9.0=py312hecd8cb5_0
  - typing-extensions=4.11.0=py312hecd8cb5_0
  - typing_extensions=4.11.0=py312hecd8cb5_0
  - tzdata=2024a=h8827d51_1
  - unicodedata2=15.1.0=py312h6c40b1e_0
  - urllib3=2.2.2=py312hecd8cb5_0
  - utf8proc=2.6.1=h6c40b1e_1
  - visions=0.7.6=py312hecd8cb5_0
  - voila=0.5.7=py312hecd8cb5_0
  - wasabi=0.9.1=py312hecd8cb5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - weasel=0.3.4=py312hecd8cb5_0
  - webencodings=0.5.1=py312hecd8cb5_2
  - websocket-client=1.8.0=py312hecd8cb5_0
  - websockets=10.4=py312h6c40b1e_1
  - werkzeug=3.0.3=py312hecd8cb5_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.10=py312hecd8cb5_0
  - wordcloud=1.9.3=py312h6c40b1e_0
  - wrapt=1.14.1=py312h6c40b1e_0
  - xgboost=2.1.1=cpu_pyhb8f9a19_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xorg-libxau=1.0.11=h0dc2134_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xxhash=0.8.0=h9ed2024_3
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=haf1e3a3_0
  - yarl=1.11.0=py312h46256e1_0
  - ydata-profiling=4.8.3=py312hecd8cb5_0
  - zeromq=4.3.5=hcec6c5f_0
  - zfp=1.0.1=h28dbb38_1
  - zict=3.0.0=py312hecd8cb5_0
  - zipp=3.17.0=py312hecd8cb5_0
  - zlib=1.3.1=h87427d6_1
  - zlib-ng=2.0.7=h6c40b1e_0
  - zstd=1.5.6=h915ae27_0
  - pip:
      - autokeras==2.0.0
      - causal-learn==0.1.3.8
      - econml==0.15.1
      - kagglehub==0.3.0
      - keras-nlp==0.15.0
      - lightgbm==4.5.0
      - python-graphviz==0.20.3
      - sparse==0.15.4
      - split-folders==0.5.1
